---
# tasks file for roles/base
- name: Install dependencies
  apt:
    name:
      - net-tools
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes