---
- name: Baseline Configuration
  hosts: workers
  remote_user: vagrant
  become: yes
  roles:
    - role: base

- name: Apache
  hosts: workers
  remote_user: vagrant
  become: yes
  roles:
    - role: apache