---
# tasks file for kubeadm

#- name: Install Kubeadm on masters
#  shell: curl -fsSL https://luc.run/kubeadm/controlplane.sh | sh
#  when: "'masters' in group_names"
- name: Add Kubernetes apt key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes repo
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes

- name: Install kubelet, kubeadm, kubectl
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: Hold kube packages
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    mark_hold: yes

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Download kubeadm master script
  get_url:
    url: https://luc.run/kubeadm/controlplane.sh
    dest: /tmp/controlplane.sh
    mode: '0755'
  when: "'masters' in group_names"
#
- name: Run kubeadm master script asynchronously
  command: bash /tmp/controlplane.sh
  when: "'masters' in group_names"

- name: Download kubeadm worker script
  get_url:
    url: https://luc.run/kubeadm/worker.sh
    dest: /tmp/worker.sh
    mode: '0755'
  when: "'workers' in group_names"

- name: Run kubeadm worker script asynchronously
  command: bash /tmp/worker.sh
  when: "'workers' in group_names"

# Download kubeadm master script
#- name: Download kubeadm master script
#  get_url:
#    url: https://luc.run/kubeadm/controlplane.sh
#    dest: /tmp/controlplane.sh
#    mode: '0755'
#  when: "'masters' in group_names"
#
## Download kubeadm worker script
#- name: Download kubeadm worker script
#  get_url:
#    url: https://luc.run/kubeadm/worker.sh
#    dest: /tmp/worker.sh
#    mode: '0755'
#  when: "'workers' in group_names"
